# Generated by Django 6.0.3 on 2026-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysetting",
            name="email",
            field=models.EmailField(default="mayaaqua26@gmail.com", max_length=254),
        ),
    ]
